var firstname = "Arjun";
var lastname = "Menon";
var a = 10 ;
var b = 5 ;
var c = 0 ;
var d = 5 ;
var e = 4 ;
var f = 46 ;
var g = 1 ; 
var h = 1 ; 
var add = a + b ; 
var add2 = c + d ; 
var add3 = e + f ;
var add4 = g + h ;
var concat = firstname +  lastname;
console.log(concat);
console.log(add);
console.log(add2);
console.log(add3);
console.log(add4);